### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sssan-tech** [sssan-tech/protospace-41472#1]
#URL
https://protospace-41472.onrender.com

**Comment by TakashiKozuma** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- ユーザー詳細画面で「〇〇さんの情報」「〇〇さんのプロトタイプ」が正しく表示されていません。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sssan-tech** [comment]
さっそくのご確認をありがとうございました。

差し替え箇所を見落としており大変失礼いたしました。
”ユーザー名”のテキストが、該当情報に置き換わるようコードを書きなおしました。

また、最初にデプロイを行った時点では画像がきちんと表示されていたのですが
レビューをいただいた後から、本番環境で画像がきちんと表示されていないようです。
コードの変更はしていないのですが、なにかわたしの作業がまちがってしまっているでしょうか。。
ちなみに、ローカル環境ではきちんと画像表示を確認できております。

再度お手数ですが、ご確認をお願いできますと幸いです。
（このあとフォームを再提出いたします。）

**Comment by shodai-ito** [comment]
ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

いただいた質問ですが、作業間違いではございません！
ActiveStorageの仕様上、デプロイをし直すと画像が表示されなくなっております。
通常の挙動ですのでご安心くださいませ。

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sssan-tech** [comment]
「ActiveStorageの仕様上、デプロイをし直すと画像が表示されなくなる」とのご回答をありがとうございました。
大変安心いたしました！

また、ご確認をありがとうございました。
最終課題も引き続き頑張りたいと思います！
